os: linux
language: java
jdk:
- openjdk8
if: |
  (branch IN (master, dev) AND commit_message !~ /^(bumped version to|release:) (\d+(\.\d+){2})(-.+)?$/) \
  OR tag =~ /^(\d+(\.\d+){2})([-+][\w\-\.+]+)?$/
git:
  depth: false
env:
  global:
  - MAVEN_LOG_OPTS="-D org.slf4j.simpleLogger.showDateTime=true -D org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS"
  - MAVEN_CLI_OPTS="-B -V -e -ff ${MAVEN_LOG_OPTS}"
  - PLUGIN_CLI_OPTS="${MAVEN_CLI_OPTS} --settings .travis/mvn-settings.xml -P mvn-release"
  - secure: CwBIPWIL2THGmCTUKkcVqsv02SBDlORzcs0f7cK47Xv9+SRZVqshQ+GUqk3g9Mi6b3h3kb0f+LSPi7T10CYST8R0KgrjQ437GfxwhN6kMA4N1bVjQVhgZ4t+RbY15cxGXLNN6xdYFb0QQ1u66k+VOzrB+V1EF35lWesNDa5rayiMUfOdXWF9MW0QLOu2zwmRUOu1pbuyzDXzeMdDC6y/OYyYJpjVmn/bpC8CQPgVN5rN4ho7oBVFqcv96AcHnpeLdSOLMNrwa2qs6/UcClFXXtRiiHi+MtLsOitnI/LnF+fER0A5XDiqEvEVKYBZLVFJ9qiVo57gFP0oiiHa8mt6lzFG7QPPv+kUVePe4gxyYAyHu86n91BPL76FXgdKVm4cNPs78bYmqZRyww4tG4wQDsKr5hdq5yey/7FAmvirCfVBrcLHKkWRRsrlCiEvYEWMpSRXTqGvFskeumFH0snC4o6+fTo9R9PWnfHU/IPZMa7KU0MNW/jMw/XrKcf7/OE5bPkDq7SPcXuvqb9Rlrn/6Dc7SZWMK6vbS9s3DGzZIobJL3n1TyBss2U3T3Vtqm6gMWmjtEn7iKG9NLW3P74wVwgO+qLIl11O2kJTbRlwihqXJCiQOeEsY+asdiUTL8A+dnP6V8il+2OB+gxKK/KfgkR70Dh+502Wr77dDwCni40=
  - secure: HPTcRQvzWSzv5puLNtqjQf+zbwU57N71ANvasWv6iGjdmxk9A062qkG+z7oMCU5xYjrdshGPq50X6eqsj62qpe+188xSiq20m9QCuv7ueKdBYDC6YHYQQwjopSETM3pU3Ou0c5q1jClmy6EAd55hLkskjpgfeuVT2AMMSo1BOFaR4g25rKA16F4U+svxXVarXdHwVpkIXInTHXPLkLuWLOBWLXDCB/8gk99oVFu9vCs374bklOcm8AZkhdmbcyPZBlIJfEErDDnKXAEzeQWBBNgJRjHY1/drJUkfUQ0elfahYiSZ+PE5wNhoItyuqskmMHprIpowPRSby+SJheBcOR/5kVQ7lwU5d52o8k9mPq6rxnxs57JYkPR5ai/ithS1S9PXuXcDp8xTCjB048uXfm9uufXWw3ldQJrzngeYibzaUlHbUiRunVPWw13K8oKYwVcacNFlO5RlgSe8TZ75avxhaOz+curxr5eAcqkjet7Z95xxBwPJMxLztGTrJPE2HMYFjiEf6tcWem0eBSNfl93ucdqW6R9V8a421q7FB233l2Xq+s5Unz26NicezCzJh5diwxqpYjbNCGbt7Mc++RcfDQ3XHFi2fyVoMWyiJCxDiqfHLRmBNg7LDV6tdNzIBONoswN7DpjT6TVvvJUS+DNruwiAO1ZO/aujh7ozLE8=
  - secure: Bx5cRzD00+FUw2+kgeYGzPo6N5c2KkaaPyq/a7e6rT+8Po0pQ5gwltl2W9icSE/rGBpFizb5SNTYWQAUkljn18CFm8I2m3cNdOh7ox67nRw3XCso9R9KyWJndqrKeasBrn6x5FgR96oKyvVMIkUDEFYGJwhLkjIsHRbqf66FdrCs+YKLDYP+EfUKp685h65rBs3oHitkhMVtNmUqYfcaeQIUUdlZ17O+tAXpCdwQz4GyDLo5V5RzkmSlDhSyOJJIA6HoseuVJi36CGHFkbWKidKjyV3Nz2IoIIjjVz0ShLsDH11X3AfWtd9UwDPakVqrtfszjs9/HDNY/delMPvoLmHzsY48BcNOH2SLrw2BSdTUHRjVGRx886n2pYPSJHsQ96S691C014+F6Fh+MwukdMankKP0sVbIhXKhbDQfirJnXTop9Z+pMuMurJHtGoZYxKfGcH4SBmpVbg1mUQ8uLEyH1Bz3dMZsIZgyWDLEsjZcangTXF5HX9+yHZZqM0YRcXYkJe8+sZ1Mo3+zxS7QJitPbaN1yCV9GXU7cEdMFW7Z+627ITbszJoaz8odzyJDpSWWhDwvUjNziKyqFxpNZlriQiKGEX0XbgSp6C7hYcel+P5NCf12iTMD4yzcIuGRcuDZnWAD545wIzMxiTslfCrYu16nE42b0NDD16R7oFQ=
  - secure: SVrquyFFO3RXCIr4P3RviVd60R3Bu08C4Jr4EttDfQf04YUScwbxWCi4bSZ0FCwIQTuTChjeDJcEUzqeFA3JpmnO5M7Q48xyA6NKVZ5Sz9YdYLn2p6mZf3+D0eMCcm9yqxIPWPz470Zr3ed8nnSrOK/MAjp0UaLpLFFX5xWnCWr5Q4IodGU4608ehrXj468JPXHX/KSLhiTksXCg0c2MduvUEOQe1Qt1MGv61Exaf0PmJJFnuCvRhLo+q+//i96Q/6CYjTFQvR1K57JOLYO5jmp0wgZoSS/wZ+J6wKKDM3jPkhUGOLwXTTNR8A154sekfChgRC+4zuP4/9qtUJv8f09mYg1mzChrvqYtDTL1C+asu6udqfk0lgALA8Dzh7j8bA+iSzER8jvcMgZ7VA6Tnuejh3vtS7WNwsCMIKbzlJjQndxiEQZSkMZXiJyKgpto+iGiafw4eIfkdkXqJFPkYqq9tWuIoYFC0oyPAwyabl8nfZl1zVmJD56Xrz8crj2Mje8hhLw8qbrkYo8n7Zz/RftpypLiL5R5iudL24ny20DkT6jt49J7PlAsEtRJawl/d66NYaHkShmEY7jHfrZI66j1+6mVcZtvih0eCfi/B08MYELbPMEzGKqklvDbm4I7ve4T3HmmVqm+JsDxf7Uh2UQkN0YwGqsbXY/RKKY1r4g=
  - secure: 5ZIWuCiEUm7rlRjFENjRT2xixgLiJsz0VAkj5eW+2A47QKwBuraxjg3vZxxzogeA1tFSw9ADpK2FMh4Julh/zkYWOm0cV1FJDv/60Y5waMjPyrij51LyYApQgho87WlLwzoxZIoCZ3G6I4Zf5wT7oAHiLuOJAccycqH+wMmnG0xpmgubotgdK0I4YWwKYQd9CHc6T3KxpJg7eoGTYMNpKhwDqeTIlozH3wmVkDIO/pE5vicuBOJjAwnKuUWeWBTb+56b+YGY+hfcxpEzkPO7dM2kKF7VRX5c+sbEKlx6YTbKG0BwKGLYmvHxQ57mSc7nioQ7Cex7Wuu9AhL+iY3NlV2c1ABLz5PGsMMJLmmKBqm1d0aCswi53wImS2mzdEf/nUqedbWNO6fxzsmxdXt0v68D6qQsefxom/V6x6N6oP1wdGyhuw50zJ2sEMDZoi5FqD0flMankSl8woM/xX7Xji9xi6MoU3f8uoOKFpcZkY83Ke+1ft+BZtuS4fp8KLtOttlUsSwOsN7MCk+72WOV+6QB+R8bSI3NRY24BVEgyipwA20rtcBqWB6m1IuX/HcjteqXgQqU/t8DvfvDStvBTeg9Mx0DXwyYGztqKDsa7HrmpTSpv33ADVoRbcPUxc2OvOLPioQnKt8R5ndyzxFlftr+ABcm8SrlWccym8fLZ3k=
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
before_install:
- git config --global user.name "Travis CI"
- git config --global user.email "travis.ci@yi.team"
- chmod +x ./mvnw .travis/*.sh
- git log --graph --full-history --all --color --date=short --pretty=format:"%Cred%x09%h %Creset%ad%Cgreen%d %Creset %s %C(bold)(%an)%Creset" || true
install: "/bin/true"
script:
- ./mvnw ${MAVEN_CLI_OPTS} clean install
- ./mvnw ${PLUGIN_CLI_OPTS} -D gitlog.toRef=${TRAVIS_BRANCH} -D gitlog.preRelease=SNAPSHOT semantic-gitlog:derive -U
before_deploy:
- openssl aes-256-cbc -K $encrypted_93173be662cc_key -iv $encrypted_93173be662cc_iv
  -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
deploy:
- provider: script
  skip_cleanup: true
  cleanup: false
  script: ".travis/deploy-snapshot.sh"
  on:
    branch: master
- provider: script
  skip_cleanup: true
  cleanup: false
  script: ".travis/deploy-release.sh"
  on:
    tags: true
