os: linux
language: java
jdk:
- openjdk8
install: "/bin/true"
env:
  global:
  - MAVEN_LOG_OPTS="-Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS"
  - MAVEN_CLI_OPTS="-B -V -e -ff ${MAVEN_LOG_OPTS}"
  - secure: CwBIPWIL2THGmCTUKkcVqsv02SBDlORzcs0f7cK47Xv9+SRZVqshQ+GUqk3g9Mi6b3h3kb0f+LSPi7T10CYST8R0KgrjQ437GfxwhN6kMA4N1bVjQVhgZ4t+RbY15cxGXLNN6xdYFb0QQ1u66k+VOzrB+V1EF35lWesNDa5rayiMUfOdXWF9MW0QLOu2zwmRUOu1pbuyzDXzeMdDC6y/OYyYJpjVmn/bpC8CQPgVN5rN4ho7oBVFqcv96AcHnpeLdSOLMNrwa2qs6/UcClFXXtRiiHi+MtLsOitnI/LnF+fER0A5XDiqEvEVKYBZLVFJ9qiVo57gFP0oiiHa8mt6lzFG7QPPv+kUVePe4gxyYAyHu86n91BPL76FXgdKVm4cNPs78bYmqZRyww4tG4wQDsKr5hdq5yey/7FAmvirCfVBrcLHKkWRRsrlCiEvYEWMpSRXTqGvFskeumFH0snC4o6+fTo9R9PWnfHU/IPZMa7KU0MNW/jMw/XrKcf7/OE5bPkDq7SPcXuvqb9Rlrn/6Dc7SZWMK6vbS9s3DGzZIobJL3n1TyBss2U3T3Vtqm6gMWmjtEn7iKG9NLW3P74wVwgO+qLIl11O2kJTbRlwihqXJCiQOeEsY+asdiUTL8A+dnP6V8il+2OB+gxKK/KfgkR70Dh+502Wr77dDwCni40=
  - secure: HPTcRQvzWSzv5puLNtqjQf+zbwU57N71ANvasWv6iGjdmxk9A062qkG+z7oMCU5xYjrdshGPq50X6eqsj62qpe+188xSiq20m9QCuv7ueKdBYDC6YHYQQwjopSETM3pU3Ou0c5q1jClmy6EAd55hLkskjpgfeuVT2AMMSo1BOFaR4g25rKA16F4U+svxXVarXdHwVpkIXInTHXPLkLuWLOBWLXDCB/8gk99oVFu9vCs374bklOcm8AZkhdmbcyPZBlIJfEErDDnKXAEzeQWBBNgJRjHY1/drJUkfUQ0elfahYiSZ+PE5wNhoItyuqskmMHprIpowPRSby+SJheBcOR/5kVQ7lwU5d52o8k9mPq6rxnxs57JYkPR5ai/ithS1S9PXuXcDp8xTCjB048uXfm9uufXWw3ldQJrzngeYibzaUlHbUiRunVPWw13K8oKYwVcacNFlO5RlgSe8TZ75avxhaOz+curxr5eAcqkjet7Z95xxBwPJMxLztGTrJPE2HMYFjiEf6tcWem0eBSNfl93ucdqW6R9V8a421q7FB233l2Xq+s5Unz26NicezCzJh5diwxqpYjbNCGbt7Mc++RcfDQ3XHFi2fyVoMWyiJCxDiqfHLRmBNg7LDV6tdNzIBONoswN7DpjT6TVvvJUS+DNruwiAO1ZO/aujh7ozLE8=
  - secure: Bx5cRzD00+FUw2+kgeYGzPo6N5c2KkaaPyq/a7e6rT+8Po0pQ5gwltl2W9icSE/rGBpFizb5SNTYWQAUkljn18CFm8I2m3cNdOh7ox67nRw3XCso9R9KyWJndqrKeasBrn6x5FgR96oKyvVMIkUDEFYGJwhLkjIsHRbqf66FdrCs+YKLDYP+EfUKp685h65rBs3oHitkhMVtNmUqYfcaeQIUUdlZ17O+tAXpCdwQz4GyDLo5V5RzkmSlDhSyOJJIA6HoseuVJi36CGHFkbWKidKjyV3Nz2IoIIjjVz0ShLsDH11X3AfWtd9UwDPakVqrtfszjs9/HDNY/delMPvoLmHzsY48BcNOH2SLrw2BSdTUHRjVGRx886n2pYPSJHsQ96S691C014+F6Fh+MwukdMankKP0sVbIhXKhbDQfirJnXTop9Z+pMuMurJHtGoZYxKfGcH4SBmpVbg1mUQ8uLEyH1Bz3dMZsIZgyWDLEsjZcangTXF5HX9+yHZZqM0YRcXYkJe8+sZ1Mo3+zxS7QJitPbaN1yCV9GXU7cEdMFW7Z+627ITbszJoaz8odzyJDpSWWhDwvUjNziKyqFxpNZlriQiKGEX0XbgSp6C7hYcel+P5NCf12iTMD4yzcIuGRcuDZnWAD545wIzMxiTslfCrYu16nE42b0NDD16R7oFQ=
  - secure: 8JES2zJjU9xdUpYDKy0osWMly0vHzYLXchneIN6pFGTC6RxxLyZ4MkT+oP4/mafB+Zgw1hJx2PZa6paadYkfacaW3I1KqkJjixWzWwz+RMfypGR5VNCZVcmFgCeQtZF9r6dBFN2ydefXmFwk2hPf8wLYNJfw0sv515hQ8RvPKdt0PGoozG60vz/dS50oYnFKT9PtCkdJ8tFQvwmDbZnBq6oKLZnvwNE2YxxWRvpG2FzHNnE2lIP4lVWgyGK+vbNmCyakqNVSqc60T6dsknExXYM7IVFtg9uXmrCQv1a3Rwqxc/EorN97koYo4E08jQ8cuxBOK1sUPmqK34TmXWjwcQoi4R6iFUx9eD2JnTibWfp0hQ7ELYMCmnw/JN7UwvDl86YHGAL87m10tPCWpO9H3dkAjOSubKRNt5OKuWwXj5IE/UlGlxyBvBinFFXRHUlo8CT1X8xN7+8p4UFbDmm8ZViHN6OLrQwv6YsDR/LmtGt66Y4VjARdX2PDanum+J8KL6sumx0X6blq+qj/X9Je6Nn8WYCVB+P1tmu964N5yjIuQwwdpNw5iWgBvXpbbgDm3kOh9ndfFq1vxbTfw4IhloCEBO9NbPagWF0em13CtaSilKpxw1ibe93aBH/YmSRbbupsBRknRwMi0rQ7JIPA1yYc/xeeIu8A8nlpGAwOpLc=
  - secure: 5ZIWuCiEUm7rlRjFENjRT2xixgLiJsz0VAkj5eW+2A47QKwBuraxjg3vZxxzogeA1tFSw9ADpK2FMh4Julh/zkYWOm0cV1FJDv/60Y5waMjPyrij51LyYApQgho87WlLwzoxZIoCZ3G6I4Zf5wT7oAHiLuOJAccycqH+wMmnG0xpmgubotgdK0I4YWwKYQd9CHc6T3KxpJg7eoGTYMNpKhwDqeTIlozH3wmVkDIO/pE5vicuBOJjAwnKuUWeWBTb+56b+YGY+hfcxpEzkPO7dM2kKF7VRX5c+sbEKlx6YTbKG0BwKGLYmvHxQ57mSc7nioQ7Cex7Wuu9AhL+iY3NlV2c1ABLz5PGsMMJLmmKBqm1d0aCswi53wImS2mzdEf/nUqedbWNO6fxzsmxdXt0v68D6qQsefxom/V6x6N6oP1wdGyhuw50zJ2sEMDZoi5FqD0flMankSl8woM/xX7Xji9xi6MoU3f8uoOKFpcZkY83Ke+1ft+BZtuS4fp8KLtOttlUsSwOsN7MCk+72WOV+6QB+R8bSI3NRY24BVEgyipwA20rtcBqWB6m1IuX/HcjteqXgQqU/t8DvfvDStvBTeg9Mx0DXwyYGztqKDsa7HrmpTSpv33ADVoRbcPUxc2OvOLPioQnKt8R5ndyzxFlftr+ABcm8SrlWccym8fLZ3k=
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
before_install:
- chmod +x ./mvnw
- chmod +x ./deploy.sh
script:
- ./mvnw ${MAVEN_CLI_OPTS} clean install
- ./mvnw ${MAVEN_CLI_OPTS} --settings "${TRAVIS_BUILD_DIR}/.travis/mvn-settings.xml"
  -P release-plugin
  -D gitlog.toRef=refs/heads/${TRAVIS_BRANCH}
  -D gitlog.preRelease=SNAPSHOT
  semantic-gitlog:derive -U
before_deploy:
- openssl aes-256-cbc -K $encrypted_93173be662cc_key -iv $encrypted_93173be662cc_iv
  -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
deploy:
- provider: script
  skip_cleanup: true
  cleanup: false
  script: "./deploy.sh"
  on:
    branch: master
- provider: script
  skip_cleanup: true
  cleanup: false
  script: "./deploy.sh"
  on:
    tags: true
